# Generated by Django 5.2.16 on 2026-08-03 11:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observed_url', models.URLField(blank=True, max_length=2048)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stable_key', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('canonical_title', models.TextField(blank=True)),
                ('canonical_url', models.URLField(max_length=2048)),
                ('identity_basis', models.JSONField(default=dict)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_identities', to='collections.publicationcollection')),
            ],
            options={
                'ordering': ('collection__authority__name', 'canonical_title', 'canonical_url'),
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_content_sha256', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('title', models.TextField(blank=True)),
                ('canonical_url', models.URLField(max_length=2048)),
                ('language_hint', models.CharField(blank=True, max_length=32)),
                ('plain_content', models.TextField()),
                ('normalized_metadata', models.JSONField(default=dict)),
                ('extractor_name', models.CharField(max_length=128)),
                ('extractor_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.documentidentity')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NormalizedSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('section_type', models.CharField(max_length=32)),
                ('heading', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('text_sha256', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('char_start', models.PositiveBigIntegerField()),
                ('char_end', models.PositiveBigIntegerField()),
                ('source_locator', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='documents.documentversion')),
            ],
            options={
                'ordering': ('document_version', 'ordinal'),
            },
        ),
    ]
