# Generated by Django 5.2.16 on 2026-08-03 11:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0002_initial'),
        ('documents', '0001_initial'),
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedsection',
            name='extraction_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_sections', to='extraction.extractionrun'),
        ),
        migrations.AddField(
            model_name='normalizedsection',
            name='source_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_sections', to='artifacts.rawartifact'),
        ),
        migrations.AddField(
            model_name='normalizedsection',
            name='source_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_section', to='extraction.extractedblock'),
        ),
        migrations.AddField(
            model_name='versionevidence',
            name='artifact_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_version_evidence', to='artifacts.artifactobservation'),
        ),
        migrations.AddField(
            model_name='versionevidence',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_records', to='documents.documentversion'),
        ),
        migrations.AddField(
            model_name='versionevidence',
            name='extraction_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='version_evidence', to='extraction.extractionrun'),
        ),
        migrations.AddField(
            model_name='versionevidence',
            name='raw_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_version_evidence', to='artifacts.rawartifact'),
        ),
        migrations.AddIndex(
            model_name='documentidentity',
            index=models.Index(fields=['collection', 'canonical_url'], name='documents_d_collect_bde447_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['identity', 'created_at'], name='documents_d_identit_0e4d86_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('identity', 'normalized_content_sha256'), name='unique_normalized_version_per_identity'),
        ),
        migrations.AddIndex(
            model_name='normalizedsection',
            index=models.Index(fields=['document_version', 'page_number', 'ordinal'], name='documents_n_documen_9df94b_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedsection',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('heading', 'text', config='simple'), name='normalized_section_fts'),
        ),
        migrations.AddConstraint(
            model_name='normalizedsection',
            constraint=models.UniqueConstraint(fields=('document_version', 'ordinal'), name='unique_normalized_section_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='normalizedsection',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gte', models.F('char_start'))), name='normalized_section_char_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='versionevidence',
            constraint=models.UniqueConstraint(fields=('document_version', 'raw_artifact', 'extraction_run'), name='unique_version_artifact_extraction_evidence'),
        ),
    ]
