# Generated by Django 5.2.16 on 2026-08-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_initial'),
        ('documents', '0002_initial'),
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='versionevidence',
            name='unique_version_artifact_extraction_evidence',
        ),
        migrations.AlterField(
            model_name='normalizedsection',
            name='source_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_sections', to='extraction.extractedblock'),
        ),
        migrations.AlterField(
            model_name='versionevidence',
            name='artifact_observation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_version_evidence', to='artifacts.artifactobservation'),
        ),
        migrations.AlterField(
            model_name='versionevidence',
            name='extraction_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='version_evidence_records', to='extraction.extractionrun'),
        ),
    ]
