# Generated by Django 5.2.16 on 2026-08-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_versionevidence_unique_version_artifact_extraction_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentidentity',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_identities', to='documents.documentidentity'),
        ),
        migrations.AddField(
            model_name='documentidentity',
            name='supersession_basis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
