# Generated by Django 5.2.16 on 2026-08-03 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('not_modified', 'Not modified'), ('retryable_failure', 'Retryable failure'), ('permanent_failure', 'Permanent failure'), ('quarantined', 'Quarantined')], db_index=True, default='running', max_length=32)),
                ('requested_url', models.URLField(max_length=2048)),
                ('final_url', models.URLField(blank=True, max_length=2048)),
                ('request_headers', models.JSONField(default=dict)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(default=dict)),
                ('redirect_chain', models.JSONField(default=list)),
                ('resolved_addresses', models.JSONField(default=list)),
                ('bytes_received', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fetch_attempts', to='discovery.discoveredcandidate')),
                ('source_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fetch_attempts', to='discovery.sourcerun')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['candidate', 'status', 'created_at'], name='fetching_fe_candida_67acad_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_run', 'candidate', 'attempt_number'), name='unique_fetch_attempt_number_per_observation')],
            },
        ),
    ]
