# Generated by Django 5.2.17 on 2026-08-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_sourceadmissionassessment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceadmissionassessment',
            old_name='required_captures',
            new_name='required_evidence_count',
        ),
        migrations.AddField(
            model_name='sourceadmissionassessment',
            name='admission_profile',
            field=models.CharField(choices=[('browser_listing', 'Browser listing'), ('static_listing', 'Static listing')], db_index=True, default='browser_listing', max_length=24),
        ),
        migrations.AddField(
            model_name='sourceadmissionassessment',
            name='evaluated_source_run_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
