# Generated by Django 5.2.16 on 2026-08-03 10:03

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('jurisdiction', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[A-Z]{2}$', 'Use an ISO 3166-1 alpha-2 uppercase code.')])),
                ('authority_type', models.CharField(choices=[('regulator', 'Regulator'), ('ministry', 'Ministry'), ('legislature', 'Legislature'), ('gazette', 'Gazette'), ('court', 'Court'), ('central_bank', 'Central bank'), ('other', 'Other')], max_length=32)),
                ('regulatory_domains', models.JSONField(blank=True, default=list)),
                ('official_domains', models.JSONField(blank=True, default=list)),
                ('trust_classification', models.CharField(choices=[('authoritative', 'Authoritative'), ('official_signal', 'Official signal'), ('verified_secondary', 'Verified secondary'), ('discovery_only', 'Discovery only'), ('untrusted', 'Untrusted')], default='authoritative', max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'authorities',
                'ordering': ('country_code', 'name'),
            },
        ),
    ]
