# Generated by Django 5.2.16 on 2026-08-03 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('discovery_url', models.URLField(max_length=2048)),
                ('connector_type', models.CharField(choices=[('rss', 'RSS or Atom'), ('html_listing', 'Static HTML listing'), ('direct_document', 'Direct document'), ('sitemap', 'Sitemap'), ('rest_api', 'REST API'), ('javascript_listing', 'JavaScript listing'), ('email', 'Email'), ('manual_upload', 'Manual upload')], max_length=32)),
                ('allowed_domains', models.JSONField(default=list)),
                ('polling_interval_minutes', models.PositiveIntegerField(default=60)),
                ('next_poll_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pagination_strategy', models.CharField(choices=[('none', 'None'), ('page', 'Page number'), ('cursor', 'Cursor'), ('next_link', 'Next link'), ('load_more', 'Load more')], default='none', max_length=32)),
                ('expected_content_types', models.JSONField(blank=True, default=list)),
                ('requires_javascript', models.BooleanField(default=False)),
                ('connector_configuration_version', models.PositiveIntegerField(default=1)),
                ('last_successful_run_at', models.DateTimeField(blank=True, null=True)),
                ('health_state', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy'), ('disabled', 'Disabled')], db_index=True, default='unknown', max_length=16)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_endpoints', to='collections.publicationcollection')),
            ],
            options={
                'ordering': ('collection__authority__name', 'collection__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ConnectorConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('configuration', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_configurations', to='sources.sourceendpoint')),
            ],
            options={
                'ordering': ('endpoint', '-version'),
            },
        ),
        migrations.AddIndex(
            model_name='sourceendpoint',
            index=models.Index(fields=['is_enabled', 'next_poll_at'], name='sources_sou_is_enab_3a4a80_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceendpoint',
            constraint=models.UniqueConstraint(fields=('collection', 'name'), name='unique_endpoint_name_per_collection'),
        ),
        migrations.AddConstraint(
            model_name='sourceendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('polling_interval_minutes__gte', 1)), name='source_poll_interval_at_least_one_minute'),
        ),
        migrations.AddConstraint(
            model_name='connectorconfiguration',
            constraint=models.UniqueConstraint(fields=('endpoint', 'version'), name='unique_connector_configuration_version'),
        ),
    ]
