# Generated by Django 5.2.16 on 2026-08-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceendpoint",
            name="consecutive_failures",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sourceendpoint",
            name="last_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourceendpoint",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
