# Generated by Django 5.2.16 on 2026-08-03 17:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0002_initial'),
        ('collections', '0001_initial'),
        ('documents', '0003_remove_versionevidence_unique_version_artifact_extraction_evidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAssessmentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruleset', models.CharField(max_length=128)),
                ('configuration', models.JSONField(default=dict)),
                ('configuration_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('corpus_fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('review_required_count', models.PositiveIntegerField(default=0)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_assessment_runs', to='collections.publicationcollection')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentQualityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Warning'), ('review_required', 'Review required')], db_index=True, max_length=32)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_assessments', to='documents.documentversion')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_quality_assessments', to='artifacts.rawartifact')),
                ('quality_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_assessments', to='quality.qualityassessmentrun')),
            ],
            options={
                'ordering': ('quality_run', 'outcome', 'document_version'),
            },
        ),
        migrations.CreateModel(
            name='QualityFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('review_required', 'Review required')], db_index=True, max_length=32)),
                ('message', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='quality.documentqualityassessment')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_findings', to='documents.documentversion')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_findings', to='artifacts.rawartifact')),
            ],
            options={
                'ordering': ('assessment', 'severity', 'code'),
            },
        ),
        migrations.AddIndex(
            model_name='qualityassessmentrun',
            index=models.Index(fields=['collection', 'status', 'created_at'], name='quality_qua_collect_b0909f_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityassessmentrun',
            constraint=models.UniqueConstraint(fields=('collection', 'configuration_hash', 'corpus_fingerprint'), name='unique_quality_run_for_collection_corpus_config'),
        ),
        migrations.AddIndex(
            model_name='documentqualityassessment',
            index=models.Index(fields=['quality_run', 'outcome'], name='quality_doc_quality_79ae20_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentqualityassessment',
            constraint=models.UniqueConstraint(fields=('quality_run', 'document_version'), name='unique_document_assessment_per_quality_run'),
        ),
        migrations.AddIndex(
            model_name='qualityfinding',
            index=models.Index(fields=['assessment', 'severity'], name='quality_qua_assessm_bfd4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityfinding',
            index=models.Index(fields=['document_version', 'code'], name='quality_qua_documen_51a557_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityfinding',
            constraint=models.UniqueConstraint(fields=('assessment', 'code'), name='unique_quality_finding_code_per_assessment'),
        ),
    ]
