# Generated by Django 5.2.16 on 2026-08-03 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('replay', 'Replay')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('connector_configuration_version', models.PositiveIntegerField()),
                ('cursor_before', models.JSONField(blank=True, null=True)),
                ('cursor_after', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_candidate_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_runs', to='sources.sourceendpoint')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DiscoveredCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovered_url', models.URLField(max_length=2048)),
                ('canonical_url', models.URLField(blank=True, max_length=2048)),
                ('external_identifier', models.CharField(blank=True, max_length=512)),
                ('fingerprint', models.CharField(max_length=64)),
                ('metadata_hints', models.JSONField(blank=True, default=dict)),
                ('pipeline_state', models.CharField(choices=[('discovered', 'Discovered'), ('fetch_pending', 'Fetch pending'), ('fetched', 'Fetched'), ('raw_stored', 'Raw stored'), ('extracted', 'Extracted'), ('normalized', 'Normalized'), ('identity_resolved', 'Identity resolved'), ('versioned', 'Versioned'), ('diffed', 'Diffed'), ('published', 'Published'), ('retryable_failure', 'Retryable failure'), ('permanent_failure', 'Permanent failure'), ('quarantined', 'Quarantined'), ('manual_review', 'Manual review')], db_index=True, default='discovered', max_length=32)),
                ('first_discovered_at', models.DateTimeField()),
                ('last_discovered_at', models.DateTimeField()),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovered_candidates', to='sources.sourceendpoint')),
                ('latest_source_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latest_candidates', to='discovery.sourcerun')),
            ],
            options={
                'ordering': ('-last_discovered_at',),
            },
        ),
        migrations.CreateModel(
            name='CandidateObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='discovery.discoveredcandidate')),
                ('source_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_observations', to='discovery.sourcerun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='sourcerun',
            index=models.Index(fields=['endpoint', 'status', 'created_at'], name='discovery_s_endpoin_f95725_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredcandidate',
            index=models.Index(fields=['endpoint', 'pipeline_state'], name='discovery_d_endpoin_0bfeed_idx'),
        ),
        migrations.AddConstraint(
            model_name='discoveredcandidate',
            constraint=models.UniqueConstraint(fields=('endpoint', 'fingerprint'), name='unique_candidate_fingerprint_per_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='candidateobservation',
            constraint=models.UniqueConstraint(fields=('source_run', 'candidate'), name='unique_candidate_observation_per_run'),
        ),
    ]
