# Generated by Django 5.2.16 on 2026-08-04 13:13

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0001_initial"),
        ("sources", "0002_sourceendpoint_consecutive_failures_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndpointObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("changed", "Changed"),
                            ("unchanged", "Unchanged"),
                            ("not_modified", "HTTP not modified"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("requested_url", models.URLField(max_length=2048)),
                ("final_url", models.URLField(max_length=2048)),
                ("response_status", models.PositiveSmallIntegerField()),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                ("redirect_chain", models.JSONField(blank=True, default=list)),
                ("resolved_addresses", models.JSONField(blank=True, default=list)),
                ("byte_size", models.PositiveBigIntegerField(default=0)),
                (
                    "content_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[django.core.validators.RegexValidator("^[0-9a-f]{64}$")],
                    ),
                ),
                ("etag", models.CharField(blank=True, max_length=512)),
                ("last_modified", models.CharField(blank=True, max_length=255)),
                ("connector_configuration_version", models.PositiveIntegerField()),
                (
                    "checked_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="endpoint_observations",
                        to="sources.sourceendpoint",
                    ),
                ),
                (
                    "previous_observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_observations",
                        to="discovery.endpointobservation",
                    ),
                ),
                (
                    "source_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="endpoint_observation",
                        to="discovery.sourcerun",
                    ),
                ),
            ],
            options={
                "ordering": ("-checked_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["endpoint", "outcome", "checked_at"],
                        name="discovery_e_endpoin_5c0e91_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(outcome="not_modified", response_status=304)
                            | models.Q(
                                outcome__in=("changed", "unchanged"),
                                response_status__gte=200,
                                response_status__lt=300,
                            )
                        ),
                        name="endpoint_observation_outcome_matches_status",
                    )
                ],
            },
        ),
    ]
