# Generated by Django 5.2.16 on 2026-08-05 03:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_endpointobservation'),
        ('sources', '0002_sourceendpoint_consecutive_failures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('detail_page', 'Detail page'), ('rss', 'RSS feed'), ('atom', 'Atom feed')], db_index=True, max_length=16)),
                ('url', models.URLField(max_length=2048)),
                ('fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('title', models.CharField(blank=True, max_length=512)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('approval_basis', models.CharField(blank=True, max_length=255)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('polling_interval_minutes', models.PositiveIntegerField(default=360)),
                ('next_poll_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_run_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('health_state', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy'), ('disabled', 'Disabled')], db_index=True, default='unknown', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitored_resources', to='sources.sourceendpoint')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='discovery.monitoredresource')),
            ],
            options={
                'ordering': ('endpoint', 'resource_type', 'url'),
            },
        ),
        migrations.CreateModel(
            name='ResourceObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('changed', 'Changed'), ('unchanged', 'Unchanged'), ('not_modified', 'HTTP not modified')], db_index=True, max_length=16)),
                ('requested_url', models.URLField(max_length=2048)),
                ('final_url', models.URLField(max_length=2048)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('redirect_chain', models.JSONField(blank=True, default=list)),
                ('resolved_addresses', models.JSONField(blank=True, default=list)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('content_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('etag', models.CharField(blank=True, max_length=512)),
                ('last_modified', models.CharField(blank=True, max_length=255)),
                ('link_set_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('link_count', models.PositiveIntegerField(default=0)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('previous_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_observations', to='discovery.resourceobservation')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='discovery.monitoredresource')),
            ],
            options={
                'ordering': ('-checked_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ResourceLinkObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField(max_length=2048)),
                ('fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('external_identifier', models.CharField(blank=True, max_length=512)),
                ('relation', models.CharField(default='document', max_length=32)),
                ('state', models.CharField(choices=[('added', 'Added'), ('retained', 'Retained'), ('removed', 'Removed')], db_index=True, max_length=16)),
                ('disposition', models.CharField(choices=[('accepted', 'Accepted'), ('quarantined', 'Quarantined')], db_index=True, max_length=16)),
                ('quarantine_reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resource_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='link_observations', to='discovery.resourceobservation')),
            ],
            options={
                'ordering': ('resource_observation', 'target_url'),
            },
        ),
        migrations.CreateModel(
            name='ResourceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('cursor_before', models.JSONField(blank=True, null=True)),
                ('cursor_after', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('observed_link_count', models.PositiveIntegerField(default=0)),
                ('accepted_candidate_count', models.PositiveIntegerField(default=0)),
                ('quarantined_link_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='discovery.monitoredresource')),
                ('source_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resource_run', to='discovery.sourcerun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='resourceobservation',
            name='resource_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='observation', to='discovery.resourcerun'),
        ),
        migrations.AddIndex(
            model_name='monitoredresource',
            index=models.Index(fields=['is_enabled', 'is_approved', 'next_poll_at'], name='discovery_m_is_enab_99ea48_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoredresource',
            index=models.Index(fields=['endpoint', 'resource_type', 'health_state'], name='discovery_m_endpoin_835923_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitoredresource',
            constraint=models.UniqueConstraint(fields=('endpoint', 'fingerprint'), name='unique_resource_fingerprint_per_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='monitoredresource',
            constraint=models.CheckConstraint(condition=models.Q(('polling_interval_minutes__gte', 1)), name='resource_poll_interval_at_least_one_minute'),
        ),
        migrations.AddIndex(
            model_name='resourcelinkobservation',
            index=models.Index(fields=['resource_observation', 'state', 'disposition'], name='discovery_r_resourc_c9236d_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourcelinkobservation',
            constraint=models.UniqueConstraint(fields=('resource_observation', 'fingerprint'), name='unique_link_per_resource_observation'),
        ),
        migrations.AddConstraint(
            model_name='resourcelinkobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('disposition', 'accepted'), ('quarantine_reason', '')), ('disposition', 'quarantined'), _connector='OR'), name='resource_link_quarantine_reason_contract'),
        ),
        migrations.AddIndex(
            model_name='resourcerun',
            index=models.Index(fields=['resource', 'status', 'created_at'], name='discovery_r_resourc_6d1be7_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceobservation',
            index=models.Index(fields=['resource', 'outcome', 'checked_at'], name='discovery_r_resourc_fd1115_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourceobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome', 'not_modified'), ('response_status', 304)), models.Q(('outcome__in', ('changed', 'unchanged')), ('response_status__gte', 200), ('response_status__lt', 300)), _connector='OR'), name='resource_observation_outcome_matches_status'),
        ),
    ]
