# Generated by Django 5.2 for ARIA reader conversations.

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0004_documentidentity_superseded_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReaderChatThread",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=160)),
                ("status", models.CharField(choices=[("active", "Active"), ("archived", "Archived")], db_index=True, default="active", max_length=16)),
                ("last_message_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("document_identity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reader_chat_threads", to="documents.documentidentity")),
                ("document_version", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reader_chat_threads", to="documents.documentversion")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reader_chat_threads", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-last_message_at", "-created_at")},
        ),
        migrations.CreateModel(
            name="ReaderChatMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("user", "User"), ("assistant", "Assistant")], max_length=16)),
                ("content", models.TextField()),
                ("provider", models.CharField(blank=True, max_length=64)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("provider_response_id", models.CharField(blank=True, max_length=255)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("suggested_questions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("thread", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="reader.readerchatthread")),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.CreateModel(
            name="ReaderChatCitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ordinal", models.PositiveIntegerField()),
                ("excerpt", models.TextField()),
                ("section_text_sha256", models.CharField(max_length=64)),
                ("artifact_sha256", models.CharField(max_length=64)),
                ("document_version_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="citations", to="reader.readerchatmessage")),
                ("normalized_section", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reader_chat_citations", to="documents.normalizedsection")),
            ],
            options={"ordering": ("ordinal", "id")},
        ),
        migrations.AddIndex(
            model_name="readerchatthread",
            index=models.Index(fields=["owner", "status", "last_message_at"], name="reader_read_owner_i_685235_idx"),
        ),
        migrations.AddIndex(
            model_name="readerchatthread",
            index=models.Index(fields=["owner", "document_identity", "status"], name="reader_read_owner_i_5f0092_idx"),
        ),
        migrations.AddIndex(
            model_name="readerchatmessage",
            index=models.Index(fields=["thread", "created_at"], name="reader_read_thread__3e7918_idx"),
        ),
        migrations.AddConstraint(
            model_name="readerchatcitation",
            constraint=models.UniqueConstraint(fields=("message", "normalized_section"), name="unique_reader_chat_message_section_citation"),
        ),
    ]
