# Generated by Django 5.2.16 on 2026-08-03 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('document_family', models.CharField(choices=[('acts_regulations', 'Acts and regulations'), ('policy', 'Policy documents'), ('circular', 'Circulars'), ('guideline', 'Guidelines'), ('consultation', 'Consultation papers'), ('enforcement', 'Enforcement notices'), ('press_release', 'Press releases'), ('faq', 'FAQs'), ('other', 'Other')], max_length=32)),
                ('default_legal_status', models.CharField(blank=True, max_length=128)),
                ('is_evidence_eligible', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[(10, 'Critical'), (20, 'High'), (30, 'Normal'), (40, 'Low')], default=30)),
                ('expected_update_frequency', models.CharField(blank=True, max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_collections', to='authorities.authority')),
            ],
            options={
                'ordering': ('authority__name', 'priority', 'name'),
                'constraints': [models.UniqueConstraint(fields=('authority', 'slug'), name='unique_collection_slug_per_authority')],
            },
        ),
    ]
