# Generated by Django 5.2.16 on 2026-08-03 18:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0003_artifactderivative'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_name', models.CharField(max_length=128)),
                ('profile_version', models.CharField(max_length=64)),
                ('configuration', models.JSONField(default=dict)),
                ('configuration_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('retryable_failure', 'Retryable failure'), ('permanent_failure', 'Permanent failure')], db_index=True, default='pending', max_length=32)),
                ('toolchain', models.JSONField(blank=True, default=dict)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('non_whitespace_characters', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('searchable_pdf_derivative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='searchable_pdf_ocr_runs', to='artifacts.artifactderivative')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocr_runs', to='artifacts.rawartifact')),
                ('text_sidecar_derivative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='text_sidecar_ocr_runs', to='artifacts.artifactderivative')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['source_artifact', 'status', 'created_at'], name='ocr_ocrrun_source__3a913b_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_artifact', 'profile_name', 'profile_version', 'configuration_hash'), name='unique_ocr_configuration_per_artifact')],
            },
        ),
    ]
