# Generated by Django 5.2.17 on 2026-08-06 12:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0004_artifactobservation_content_changed'),
        ('comparisons', '0006_reviewedchangepublication'),
        ('documents', '0004_documentidentity_superseded_by_and_more'),
        ('extraction', '0001_initial'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrchestration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('waiting_ocr', 'Waiting for OCR'), ('no_content_change', 'No normalized content change'), ('quality_review_required', 'Quality review required'), ('lineage_rejected', 'Lineage rejected'), ('review_required', 'Comparison review required'), ('summary_pending', 'GPT summary pending'), ('summary_failed', 'GPT summary failed'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('current_stage', models.CharField(choices=[('artifact', 'Artifact verification'), ('extraction', 'Extraction'), ('version', 'Version resolution'), ('quality', 'Quality assessment'), ('knowledge', 'Knowledge projection'), ('lineage', 'Lineage and anchors'), ('comparison', 'Deterministic comparison'), ('review', 'Human review'), ('summary', 'GPT summary'), ('completed', 'Completed')], db_index=True, default='artifact', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('artifact_observation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='change_orchestration', to='artifacts.artifactobservation')),
                ('comparison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_orchestrations', to='comparisons.documentcomparison')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_orchestrations', to='documents.documentversion')),
                ('extraction_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_orchestrations', to='extraction.extractionrun')),
                ('lineage_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_orchestrations', to='comparisons.versionlineageassessment')),
                ('quality_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_orchestrations', to='quality.qualityassessmentrun')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_orchestrations', to='artifacts.rawartifact')),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_orchestrations', to='comparisons.comparisonsummary')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrchestrationStepAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('artifact', 'Artifact verification'), ('extraction', 'Extraction'), ('version', 'Version resolution'), ('quality', 'Quality assessment'), ('knowledge', 'Knowledge projection'), ('lineage', 'Lineage and anchors'), ('comparison', 'Deterministic comparison'), ('review', 'Human review'), ('summary', 'GPT summary'), ('completed', 'Completed')], db_index=True, max_length=16)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('waiting', 'Waiting'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('input_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('orchestration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_attempts', to='orchestration.changeorchestration')),
            ],
            options={
                'ordering': ('orchestration', 'started_at', 'attempt_number'),
            },
        ),
        migrations.AddIndex(
            model_name='changeorchestration',
            index=models.Index(fields=['status', 'heartbeat_at'], name='orchestrati_status_2e2fea_idx'),
        ),
        migrations.AddIndex(
            model_name='changeorchestration',
            index=models.Index(fields=['source_artifact', 'status'], name='orchestrati_source__a87d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationstepattempt',
            index=models.Index(fields=['orchestration', 'stage', 'outcome'], name='orchestrati_orchest_884be1_idx'),
        ),
        migrations.AddConstraint(
            model_name='orchestrationstepattempt',
            constraint=models.UniqueConstraint(fields=('orchestration', 'stage', 'attempt_number'), name='unique_orchestration_stage_attempt'),
        ),
    ]
