# Generated by Django 5.2.16 on 2026-08-03 10:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('actor_type', models.CharField(default='system', max_length=32)),
                ('actor_identifier', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.UUIDField(db_index=True)),
                ('details', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['target_type', 'target_id', 'occurred_at'], name='events_audi_target__514b0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PipelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('aggregate_type', models.CharField(db_index=True, max_length=64)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id', 'occurred_at'], name='events_pipe_aggrega_b9e916_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('pipeline_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_event', to='events.pipelineevent')),
            ],
            options={
                'ordering': ('available_at',),
                'indexes': [models.Index(fields=['status', 'available_at'], name='events_outb_status_3327b8_idx')],
            },
        ),
    ]
