# Generated by Django 5.2.16 on 2026-08-03 11:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0002_initial'),
        ('documents', '0002_initial'),
        ('knowledge', '0001_vector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_type', models.CharField(choices=[('authority', 'Authority'), ('collection', 'Collection'), ('document', 'Document identity'), ('version', 'Document version'), ('section', 'Normalized section'), ('artifact', 'Raw artifact')], db_index=True, max_length=32)),
                ('canonical_key', models.CharField(max_length=255, unique=True)),
                ('label', models.TextField(blank=True)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.UUIDField()),
                ('properties', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('node_type', 'label', 'canonical_key'),
                'indexes': [models.Index(fields=['node_type', 'source_id'], name='knowledge_g_node_ty_47f7c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id'), name='unique_graph_node_source')],
            },
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicate', models.CharField(choices=[('has_collection', 'Has collection'), ('has_document', 'Has document'), ('has_version', 'Has version'), ('has_section', 'Has section'), ('derived_from', 'Derived from')], db_index=True, max_length=64)),
                ('fingerprint', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.UUIDField()),
                ('properties', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('evidence_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graph_edges', to='artifacts.rawartifact')),
                ('evidence_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graph_edges', to='documents.normalizedsection')),
                ('evidence_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graph_edges', to='documents.documentversion')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_edges', to='knowledge.graphnode')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_edges', to='knowledge.graphnode')),
            ],
            options={
                'ordering': ('subject', 'predicate', 'object'),
                'indexes': [models.Index(fields=['subject', 'predicate'], name='knowledge_g_subject_b03d3d_idx'), models.Index(fields=['object', 'predicate'], name='knowledge_g_object__09dd3a_idx'), models.Index(fields=['source_type', 'source_id'], name='knowledge_g_source__c384de_idx')],
            },
        ),
        migrations.CreateModel(
            name='SectionEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('dimensions', models.PositiveIntegerField()),
                ('source_text_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('normalized_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embeddings', to='documents.normalizedsection')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='section_embedding_cosine_hnsw', opclasses=('vector_cosine_ops',)), models.Index(fields=['provider', 'model'], name='knowledge_s_provide_31c05f_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_section', 'provider', 'model', 'source_text_sha256'), name='unique_section_embedding_projection')],
            },
        ),
    ]
