# Generated by Django 5.2.16 on 2026-08-03 19:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0003_artifactderivative'),
        ('documents', '0004_documentidentity_superseded_by_and_more'),
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionLineageAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('representation_kind', models.CharField(choices=[('landing_html', 'Landing HTML'), ('official_pdf', 'Official PDF'), ('ocr_derived', 'OCR-derived official file'), ('unknown', 'Unknown')], db_index=True, max_length=32)),
                ('comparison_track_key', models.CharField(db_index=True, max_length=160)),
                ('provenance_status', models.CharField(choices=[('verified', 'Verified'), ('reconstructable', 'Reconstructable'), ('quarantined', 'Quarantined')], db_index=True, max_length=32)),
                ('ruleset', models.CharField(max_length=128)),
                ('configuration', models.JSONField(default=dict)),
                ('configuration_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('basis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineage_assessments', to='documents.documentversion')),
                ('extraction_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='version_lineage_assessments', to='extraction.extractionrun')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='version_lineage_assessments', to='artifacts.rawartifact')),
            ],
            options={
                'ordering': ('document_version', '-created_at'),
                'indexes': [models.Index(fields=['comparison_track_key', 'provenance_status'], name='comparisons_compari_68d359_idx'), models.Index(fields=['document_version', 'ruleset'], name='comparisons_documen_419371_idx')],
                'constraints': [models.UniqueConstraint(fields=('document_version', 'configuration_hash'), name='unique_version_lineage_assessment_config'), models.CheckConstraint(condition=models.Q(('provenance_status', 'quarantined'), models.Q(('source_artifact__isnull', False), ('extraction_run__isnull', False)), _connector='OR'), name='lineage_evidence_required_unless_quarantined')],
            },
        ),
    ]
