# Generated by Django 5.2.16 on 2026-08-03 19:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_artifactderivative'),
        ('comparisons', '0001_initial'),
        ('documents', '0004_documentidentity_superseded_by_and_more'),
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuralAnchor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruleset', models.CharField(max_length=128)),
                ('configuration_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('anchor_type', models.CharField(db_index=True, max_length=32)),
                ('canonical_key', models.CharField(max_length=255)),
                ('ordinal', models.PositiveIntegerField()),
                ('label', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('text_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('char_start', models.PositiveBigIntegerField()),
                ('char_end', models.PositiveBigIntegerField()),
                ('source_locator', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structural_anchors', to='documents.documentversion')),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structural_anchors', to='extraction.extractionrun')),
                ('normalized_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structural_anchors', to='documents.normalizedsection')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structural_anchors', to='artifacts.rawartifact')),
            ],
            options={
                'ordering': ('document_version', 'ordinal'),
                'indexes': [models.Index(fields=['document_version', 'canonical_key'], name='comparisons_documen_c341f7_idx'), models.Index(fields=['anchor_type', 'canonical_key'], name='comparisons_anchor__21a8ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('document_version', 'configuration_hash', 'ordinal'), name='unique_structural_anchor_ordinal_config'), models.CheckConstraint(condition=models.Q(('char_end__gte', models.F('char_start'))), name='structural_anchor_char_range_valid')],
            },
        ),
    ]
