# Generated by Django 5.2.16 on 2026-08-03 19:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0002_structuralanchor'),
        ('documents', '0004_documentidentity_superseded_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comparison_track_key', models.CharField(db_index=True, max_length=160)),
                ('ruleset', models.CharField(max_length=128)),
                ('configuration', models.JSONField(default=dict)),
                ('configuration_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('input_fingerprint', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('added_count', models.PositiveIntegerField(default=0)),
                ('removed_count', models.PositiveIntegerField(default=0)),
                ('modified_count', models.PositiveIntegerField(default=0)),
                ('moved_count', models.PositiveIntegerField(default=0)),
                ('format_only_count', models.PositiveIntegerField(default=0)),
                ('ambiguous_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('after_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons_as_after', to='documents.documentversion')),
                ('before_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons_as_before', to='documents.documentversion')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons', to='documents.documentidentity')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ComparisonItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('unchanged', 'Unchanged'), ('added', 'Added'), ('removed', 'Removed'), ('modified', 'Modified'), ('moved', 'Moved'), ('format_only', 'Formatting only'), ('ambiguous', 'Ambiguous')], db_index=True, max_length=16)),
                ('match_strategy', models.CharField(max_length=64)),
                ('similarity_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('text_delta', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('after_anchor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comparison_items_as_after', to='comparisons.structuralanchor')),
                ('before_anchor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comparison_items_as_before', to='comparisons.structuralanchor')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='comparisons.documentcomparison')),
            ],
            options={
                'ordering': ('comparison', 'created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='documentcomparison',
            index=models.Index(fields=['identity', 'status', 'created_at'], name='comparisons_identit_74c738_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomparison',
            index=models.Index(fields=['comparison_track_key', 'created_at'], name='comparisons_compari_25a7ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentcomparison',
            constraint=models.UniqueConstraint(fields=('before_version', 'after_version', 'configuration_hash'), name='unique_document_comparison_pair_config'),
        ),
        migrations.AddConstraint(
            model_name='documentcomparison',
            constraint=models.CheckConstraint(condition=models.Q(('before_version', models.F('after_version')), _negated=True), name='comparison_versions_differ'),
        ),
        migrations.AddIndex(
            model_name='comparisonitem',
            index=models.Index(fields=['comparison', 'change_type'], name='comparisons_compari_89dcf4_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonitem',
            index=models.Index(fields=['before_anchor', 'after_anchor'], name='comparisons_before__641bf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='comparisonitem',
            constraint=models.UniqueConstraint(fields=('comparison', 'fingerprint'), name='unique_comparison_item_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='comparisonitem',
            constraint=models.CheckConstraint(condition=models.Q(('before_anchor__isnull', False), ('after_anchor__isnull', False), _connector='OR'), name='comparison_item_has_anchor'),
        ),
    ]
