# Generated by Django 5.2.16 on 2026-08-03 19:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0003_documentcomparison_comparisonitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('needs_context', 'Needs context')], db_index=True, max_length=16)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('comparison_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='comparisons.comparisonitem')),
                ('previous_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding_reviews', to='comparisons.comparisonreview')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparison_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['comparison_item', 'created_at'], name='comparisons_compari_94ecf2_idx'), models.Index(fields=['decision', 'created_at'], name='comparisons_decisio_b6c832_idx')],
            },
        ),
    ]
