# Generated by Django 5.2.16 on 2026-08-03 19:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0004_comparisonreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='openai', max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(max_length=128)),
                ('input_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('input_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('output', models.JSONField(default=dict)),
                ('response_id', models.CharField(blank=True, max_length=255)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='comparisons.documentcomparison')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['comparison', 'status', 'created_at'], name='comparisons_compari_11aba0_idx'), models.Index(fields=['provider', 'model', 'created_at'], name='comparisons_provide_57ec39_idx')],
                'constraints': [models.UniqueConstraint(fields=('comparison', 'provider', 'model', 'prompt_version', 'input_hash'), name='unique_comparison_summary_input')],
            },
        ),
    ]
