# Generated by Django 5.2.16 on 2026-08-03 19:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0005_comparisonsummary'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewedChangePublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('comparison_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_publications', to='comparisons.comparisonitem')),
                ('confirmation_review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='change_publication', to='comparisons.comparisonreview')),
                ('pipeline_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_change_publication', to='events.pipelineevent')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['comparison_item', 'created_at'], name='comparisons_compari_bce8de_idx')],
            },
        ),
    ]
