# Generated by Django 5.2.16 on 2026-08-03 11:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extractor_name', models.CharField(max_length=128)),
                ('extractor_version', models.CharField(max_length=64)),
                ('configuration_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('ocr_required', 'OCR required'), ('retryable_failure', 'Retryable failure'), ('permanent_failure', 'Permanent failure')], db_index=True, default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('raw_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_runs', to='artifacts.rawartifact')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExtractedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('language_hint', models.CharField(blank=True, max_length=32)),
                ('plain_text', models.TextField()),
                ('plain_text_sha256', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('metadata', models.JSONField(default=dict)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_ocr', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extracted_documents', to='artifacts.rawartifact')),
                ('extraction_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='extracted_document', to='extraction.extractionrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExtractedBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('list_item', 'List item'), ('table', 'Table'), ('quote', 'Quote'), ('code', 'Code'), ('page', 'PDF page')], max_length=32)),
                ('heading_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heading', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('text_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('char_start', models.PositiveBigIntegerField()),
                ('char_end', models.PositiveBigIntegerField()),
                ('source_locator', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('extracted_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='extraction.extracteddocument')),
            ],
            options={
                'ordering': ('ordinal',),
                'indexes': [models.Index(fields=['extracted_document', 'page_number', 'ordinal'], name='extraction__extract_19cf63_idx')],
                'constraints': [models.UniqueConstraint(fields=('extracted_document', 'ordinal'), name='unique_extracted_block_ordinal'), models.CheckConstraint(condition=models.Q(('char_end__gte', models.F('char_start'))), name='extracted_block_char_range_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='extractionrun',
            index=models.Index(fields=['raw_artifact', 'status'], name='extraction__raw_art_2305c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractionrun',
            constraint=models.UniqueConstraint(fields=('raw_artifact', 'extractor_name', 'extractor_version', 'configuration_hash'), name='unique_extraction_configuration_per_artifact'),
        ),
    ]
