# Generated by Django 5.2.16 on 2026-08-03 10:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Provide a lowercase SHA-256 digest.')])),
                ('byte_size', models.PositiveBigIntegerField()),
                ('detected_content_type', models.CharField(max_length=255)),
                ('storage_backend', models.CharField(choices=[('filesystem', 'Filesystem'), ('s3', 'S3 compatible')], max_length=16)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ArtifactObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_url', models.URLField(max_length=2048)),
                ('final_url', models.URLField(max_length=2048)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_headers', models.JSONField(default=dict)),
                ('redirect_chain', models.JSONField(default=list)),
                ('retrieved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('connector_configuration_version', models.PositiveIntegerField()),
                ('etag', models.CharField(blank=True, max_length=512)),
                ('last_modified', models.CharField(blank=True, max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_observations', to='discovery.discoveredcandidate')),
            ],
            options={
                'ordering': ('-retrieved_at',),
            },
        ),
    ]
