# Generated by Django 5.2.16 on 2026-08-03 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
        ('discovery', '0001_initial'),
        ('fetching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactobservation',
            name='fetch_attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_observation', to='fetching.fetchattempt'),
        ),
        migrations.AddField(
            model_name='artifactobservation',
            name='source_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_observations', to='discovery.sourcerun'),
        ),
        migrations.AddField(
            model_name='artifactobservation',
            name='raw_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='artifacts.rawartifact'),
        ),
        migrations.AddIndex(
            model_name='artifactobservation',
            index=models.Index(fields=['candidate', 'retrieved_at'], name='artifacts_a_candida_1934fe_idx'),
        ),
    ]
