# Generated by Django 5.2.16 on 2026-08-03 18:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactDerivative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transformation_type', models.CharField(choices=[('ocr_searchable_pdf', 'OCR searchable PDF'), ('ocr_text_sidecar', 'OCR text sidecar')], db_index=True, max_length=32)),
                ('profile', models.CharField(max_length=128)),
                ('configuration_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('derived_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivations_as_output', to='artifacts.rawartifact')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derived_outputs', to='artifacts.rawartifact')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['source_artifact', 'transformation_type', 'created_at'], name='artifacts_a_source__92f40b_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_artifact', 'derived_artifact', 'transformation_type', 'configuration_hash'), name='unique_artifact_derivative_lineage'), models.CheckConstraint(condition=models.Q(('source_artifact', models.F('derived_artifact')), _negated=True), name='artifact_derivative_differs_from_source')],
            },
        ),
    ]
