# Generated by Django 5.2.16 on 2026-08-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0003_artifactderivative"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifactobservation",
            name="content_changed",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
